spring:
  application:
    name: second-service

  security:
    user:
      name: user
      password: password

server:
  port: 8081

auth:
  secret: let_me_in


logging:
  level:
    org.springframework.security: DEBUG