spring:
  application:
    name: second-service

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_for_microservice
    username: postgres
    password: postgres

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

server:
  port: 8081

auth:
  secret: let_me_in

logging:
  level:
    org.springframework.security: DEBUG